### ISSUE TITLE
template resolver enahancement

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#157]
If we use the template resolver to get the clientClass and serverClass, then customer resolvers would have less work to do. You wouldn't have to override clientClass and serverClass as they do now.

**Comment by kurtkilpela** [comment]
Right now, when the framework needs to know what the clientClass or the serverClass are, it asks the template. This usually happens shortly after the template class is resolved. Changing it so that the template resolver is used to lookup the client and server classes is pretty straight forward and seems reasonable.

I think we ought to remove the #templateClass, #clientClass, and #serverClass class methods from RsrService. We will retain the #templateClassName, #clientClassName, and #serverClassName methods. This is technically a breaking change.

If someone wishes to keep the old methods, they can add them as extensions. Their extension can retain the existing implementation of these methods.

**Comment by kurtkilpela** [comment]
Resolved by cb30aa8d09f4399e1e1c2af846365aecd62dd648
