### ISSUE TITLE
Allow Services to specify their thread priority

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/RemoteServiceReplication#72]
RSR should allow a Service to specify the scheduling priority of their processes. Once the Services are decoded we should adjust the priority of the thread based upon the Service's specification and then deliver the message to the Service.

**Comment by dalehenrich** [comment]
With the new behavior in GemStone with respect to processType (bug 49320), a service should also specify it's desired processType as well (see GsProcess>>processType:  ... values 0  process debugged by GCI; value  1  process debugged by Smalltalk) ... for my scaffolding work, I will probably go with a default of 0, since I'm not currently interested in trying to debug the RSR system threads with the RSR debugger and prefer to use topaz ... over time we can fine tune the defaults ...

**Comment by kurtkilpela** [comment]
A spike of this support is available in the kurt.ConfigureProcess branch if you'd like a sneak peek. See RsrService>>#configureProcess.

**Comment by kurtkilpela** [comment]
This is already in mainline RSR.
